const data = {
    products:[
        {
            _id: '1',
            name: 'HP Probook',
            category: 'Laptops',
            image:'/images/Laptops-hp-Pro-Book-300x275.jpg',
            price: 1150,
            brand: 'HP',
            details: 'high quality product',
            numReviews: 10,
            countInStock: 15,
        },
        {
            _id: '2',
            name: 'Canon EOS Camera',
            category: 'Cameras',
            image:'/images/Canon-EOS-Rebel-T3i.jpg',
            price: 900,
            brand: 'Canon',
            details: 'high quality product',
            numReviews: 20,
            countInStock: 50,
        },
        {
            _id: '3',
            name: 'Pro Video Camera',
            category: 'Video Camera',
            image:'/images/professional-video-camera.jpg',
            price: 5000,
            brand: 'Panasonic',
            details: 'high quality product',
            numReviews: 100,
            countInStock: 20,
        },
        {
            _id: '4',
            name: 'HTC-Google Phone',
            category: 'Phones',
            image:'/images/HTC-Google-Nexus-One-2.jpg',
            price: 520,
            brand: 'HTC',
            details: 'high quality product',
            numReviews: 120,
            countInStock: 150,
        },
        {
            _id: '5',
            name: 'Nokia Windows Tablet',
            category: 'Phones',
            image:'/images/nokia-windows-200-dollar-tablet2-640x353.jpg',
            price: 1000,
            brand: 'Nokia',
            details: 'high quality product',
            numReviews: 500,
            countInStock: 200,
        },
        {
            _id: '6',
            name: 'Dell Laptop',
            category: 'Laptops',
            image:'/images/Dell-Inspiron-R-Special-Edition.jpg',
            price: 1100,
            brand: 'Dell',
            details: 'high quality product',
            numReviews: 600,
            countInStock: 215,
        },
    ],
};

export default data;
